name: call docker workflow

on:
  push:
    branches: '*'

jobs:
  call-docker-build:
    uses: direct-devops/actions/.github/workflows/docker.yaml@main
    with:
      dockerimage: ${{ github.repository }}
      DOCKERHUB_USERNAME: ramqt2205
    secrets: inherit
    
